cxx = g++
cppflags = -Wall -pedantic-errors -ggdb
#cppflags = -Wall -pedantic-errors -O2
libraries = $(addprefix -l,GL GLU glut)
projects = convex_hull.bin minimal_circle.bin test.bin

ch_objects = $(addprefix obj/, convex_hull.o point.o geometric_algorithms.o circle.o line.o)
mec_objects = $(addprefix obj/, minimal_circle.o point.o circle.o line.o geometric_algorithms.o)
test_objects = $(addprefix obj/, test.o point.o line.o circle.o)

all: $(projects)

convex_hull.bin : $(ch_objects)
	$(cxx) $(cppflags) $(libraries) $(ch_objects) -o $@

minimal_circle.bin : $(mec_objects)
	echo hello world $(mec_objects)
	$(cxx) $(cppflags) $(libraries) $(mec_objects) -o $@

test.bin : $(test_objects)
	$(cxx) $(cppflags) $(libraries) $(test_objects) -o $@


obj/%.o: src/%.cpp
	$(cxx) $< -c $(cppflags) -Iheader -o $@

.PHONY: clean 

clean:
	-rm $(mec_objects) 
	-rm $(ch_objects)
	-rm $(projects)


#Autogenerated with
#g++ -MM -Iheader src/* | perl -pe 's/\\\n// | s#src/.*?.cpp|header/##g' | perl -pe 's/ +/ /g | s#^#obj/# | s#(: )#$1\$(addprefix(header/, # | s/$/)/' >> makefile
obj/circle.o: $(addprefix(header/, circle.h point.h)
obj/circle_interpolation.o: $(addprefix(header/, point.h geometric_algorithms.h point.h)
obj/convex_hull.o: $(addprefix(header/, point.h geometric_algorithms.h point.h)
obj/geometric_algorithms.o: $(addprefix(header/, geometric_algorithms.h point.h)
obj/line.o: $(addprefix(header/, line.h point.h)
obj/minimal_circle.o: $(addprefix(header/, point.h geometric_algorithms.h point.h)
obj/point.o: $(addprefix(header/, point.h)
obj/test.o: $(addprefix(header/, point.h line.h point.h circle.h)
